In [1]:
import cv2
import os
import pandas as pd
import plotly.express as px
import numpy as np

In [2]:
CLASSES = ['road',
        'sidewalk',
        'construction',
        'tram-track',
        'fence',
        'pole',
        'traffic-light',
        'traffic-sign',
        'vegetation',
        'terrain',
        'sky',
        'human',
        'rail-track',
        'car',
        'truck',
        'trackbed',
        'on-rails',
        'rail-raised',
        'rail-embedded']

In [3]:
path= 'rs19_val/uint8/rs19_val/'

In [4]:
filenames = ['rs08171','rs08150','rs08151','rs08160','rs00000','rs00001','rs00002','rs08498','rs08499']

In [5]:
doi={}
for file in filenames:
    temp_mask = cv2.imread(path+file+'.png')
    labels, count = np.unique(temp_mask[:,:,0], return_counts=True)
    doi[file]=dict(zip(labels,count))

In [6]:
doi.items()


dict_items([('rs08171', {1: 87902, 5: 26120, 7: 3233, 8: 407270, 9: 447899, 10: 653323, 12: 157262, 15: 247332, 17: 43259}), ('rs08150', {0: 78, 1: 16195, 2: 54206, 5: 2377, 7: 4100, 8: 615077, 9: 86385, 10: 712216, 12: 189290, 14: 30, 15: 297633, 16: 42033, 17: 29629, 255: 24351}), ('rs08151', {0: 142, 1: 1733, 2: 8302, 4: 1495, 5: 37456, 6: 1968, 7: 89, 8: 417735, 9: 136645, 10: 816357, 12: 193789, 13: 242, 15: 353649, 16: 1439, 17: 102559}), ('rs08160', {0: 20018, 1: 3964, 2: 231629, 4: 1671, 5: 128067, 6: 173, 7: 566, 8: 474661, 9: 30674, 10: 650102, 12: 193486, 13: 620, 15: 298666, 17: 35690, 255: 3613}), ('rs00000', {0: 118415, 1: 21653, 2: 1116, 5: 56914, 8: 655556, 9: 139285, 10: 637307, 12: 114931, 13: 755, 15: 254074, 17: 53742, 255: 19852}), ('rs00001', {0: 624717, 1: 89822, 2: 970974, 3: 122994, 4: 2949, 5: 3924, 6: 31, 7: 1920, 8: 35285, 10: 269, 11: 27388, 13: 13682, 18: 95845, 255: 83800}), ('rs00002', {0: 489, 1: 16878, 2: 981643, 4: 15726, 5: 211504, 8: 159767, 9: 1021

In [13]:
doi_1={}
for file in filenames:
    temp_mask = cv2.imread(path+file+'.png')
    
    temp_mask[:,:,0][temp_mask[:,:,0]== 255]=19
    print (temp_mask)

    labels, count = np.unique(temp_mask[:,:,0], return_counts=True)
    doi_1[file]=dict(zip(labels,count))

[[[10 10 10]
  [10 10 10]
  [10 10 10]
  ...
  [10 10 10]
  [10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]
  [10 10 10]
  ...
  [10 10 10]
  [10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]
  [10 10 10]
  ...
  [10 10 10]
  [10 10 10]
  [10 10 10]]

 ...

 [[15 15 15]
  [15 15 15]
  [15 15 15]
  ...
  [ 9  9  9]
  [ 9  9  9]
  [ 9  9  9]]

 [[15 15 15]
  [15 15 15]
  [15 15 15]
  ...
  [ 9  9  9]
  [ 9  9  9]
  [ 9  9  9]]

 [[15 15 15]
  [15 15 15]
  [15 15 15]
  ...
  [ 9  9  9]
  [ 9  9  9]
  [ 9  9  9]]]
[[[10 10 10]
  [10 10 10]
  [10 10 10]
  ...
  [10 10 10]
  [10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]
  [10 10 10]
  ...
  [10 10 10]
  [10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]
  [10 10 10]
  ...
  [10 10 10]
  [10 10 10]
  [10 10 10]]

 ...

 [[ 8  8  8]
  [ 8  8  8]
  [ 8  8  8]
  ...
  [17 17 17]
  [12 12 12]
  [12 12 12]]

 [[ 8  8  8]
  [ 8  8  8]
  [ 8  8  8]
  ...
  [17 17 17]
  [17 17 17]
  [12 12 12]]

 [[ 8  8  8]
  [ 8  8  8]
  [ 8  8  8]
  .

In [14]:
doi_1

{'rs08171': {1: 87902,
  5: 26120,
  7: 3233,
  8: 407270,
  9: 447899,
  10: 653323,
  12: 157262,
  15: 247332,
  17: 43259},
 'rs08150': {0: 78,
  1: 16195,
  2: 54206,
  5: 2377,
  7: 4100,
  8: 615077,
  9: 86385,
  10: 712216,
  12: 189290,
  14: 30,
  15: 297633,
  16: 42033,
  17: 29629,
  19: 24351},
 'rs08151': {0: 142,
  1: 1733,
  2: 8302,
  4: 1495,
  5: 37456,
  6: 1968,
  7: 89,
  8: 417735,
  9: 136645,
  10: 816357,
  12: 193789,
  13: 242,
  15: 353649,
  16: 1439,
  17: 102559},
 'rs08160': {0: 20018,
  1: 3964,
  2: 231629,
  4: 1671,
  5: 128067,
  6: 173,
  7: 566,
  8: 474661,
  9: 30674,
  10: 650102,
  12: 193486,
  13: 620,
  15: 298666,
  17: 35690,
  19: 3613},
 'rs00000': {0: 118415,
  1: 21653,
  2: 1116,
  5: 56914,
  8: 655556,
  9: 139285,
  10: 637307,
  12: 114931,
  13: 755,
  15: 254074,
  17: 53742,
  19: 19852},
 'rs00001': {0: 624717,
  1: 89822,
  2: 970974,
  3: 122994,
  4: 2949,
  5: 3924,
  6: 31,
  7: 1920,
  8: 35285,
  10: 269,
  11: 2738

In [99]:
wht_img=[]

for key,value in doi.items():
    item = doi[key]
    for labelKey,labelvalue in item.items():
        if  labelKey == 0:
            wht_img.append(key)


In [100]:
wht_img

['rs08150', 'rs08151', 'rs08160']

In [51]:
pixel_count = {}
label_count={}

for key in doi:
    item = doi[key]
    for labelKey in item:
        if  labelKey in pixel_count:
            pixel_count[labelKey] = pixel_count[labelKey] + item[labelKey]
            label_count[labelKey] = label_count[labelKey] + 1
        else:
            pixel_count[labelKey] = item[labelKey]
            label_count[labelKey] =1       
            
print(pixel_count)
print(label_count)

{1: 109794, 5: 194020, 7: 7988, 8: 1914743, 9: 701603, 10: 2831998, 12: 733827, 15: 1197280, 17: 211137, 0: 20238, 2: 294137, 14: 30, 16: 43472, 255: 27964, 4: 3166, 6: 2141, 13: 862}
{1: 4, 5: 4, 7: 4, 8: 4, 9: 4, 10: 4, 12: 4, 15: 4, 17: 4, 0: 3, 2: 3, 14: 1, 16: 2, 255: 2, 4: 2, 6: 2, 13: 2}


## Create a dictionary from image files against labels and respective pixel counts

In [52]:
dict_of_img={}

In [57]:
path_images = 'rs19_val/uint8/rs19_val/'

breaker = 0

for masks_img in os.listdir(path_images):
    #breaker +=1
    if masks_img.endswith('.png'):
        temp_mask = cv2.imread(path_images+masks_img)
        labels, count = np.unique(temp_mask[:,:,0], return_counts=True)
        dict_of_img[masks_img]=dict(zip(labels,count))

In [ ]:
dict_of_img

In [147]:
dict_df=pd.DataFrame(dict_of_img).T

In [148]:
dict_df.to_csv('image_label_dict_df.csv')

In [59]:
pixels = {}
labels = {}

for key in dict_of_img:
    item = dict_of_img[key]
    for labelKey in item:
        if  labelKey in pixels:
            pixels[labelKey] = pixels[labelKey] + item[labelKey]
            labels[labelKey] = labels[labelKey] + 1
        else:
            pixels[labelKey] = item[labelKey]
            labels[labelKey] =1       
            
print(pixels)
print(labels)

{0: 566749063, 1: 449090153, 2: 2114616629, 5: 482435484, 8: 4050541274, 9: 1308637386, 10: 3813778365, 12: 1078006714, 13: 66935711, 15: 1810755773, 17: 413432894, 255: 616666057, 3: 131426532, 4: 369168634, 6: 24083165, 7: 23866554, 11: 26381542, 18: 41719364, 14: 22002630, 16: 215306076}
{0: 7275, 1: 7008, 2: 8340, 5: 8359, 8: 8380, 9: 7766, 10: 8241, 12: 7772, 13: 4169, 15: 7774, 17: 7772, 255: 5902, 3: 1928, 4: 7181, 6: 4104, 7: 6072, 11: 2403, 18: 1942, 14: 1642, 16: 3210}


## make dataframe from dict and count of labels and pixels

In [68]:
df_pixel= pd.DataFrame(list(pixels.items()))
df_label= pd.DataFrame(list(labels.items()))
#pixels.items()

In [70]:
df_pixel.sort_values(by=0)
df_label.sort_values(by=0)

0     1
11  -1  5902
0    0  7275
1    1  7008
2    2  8340
12   3  1928
13   4  7181
3    5  8359
14   6  4104
15   7  6072
4    8  8380
5    9  7766
6   10  8241
16  11  2403
7   12  7772
8   13  4169
18  14  1642
9   15  7774
19  16  3210
10  17  7772
17  18  1942

In [67]:
df_pixel

0           1
0    0   566749063
1    1   449090153
2    2  2114616629
3    5   482435484
4    8  4050541274
5    9  1308637386
6   10  3813778365
7   12  1078006714
8   13    66935711
9   15  1810755773
10  17   413432894
11  -1   616666057
12   3   131426532
13   4   369168634
14   6    24083165
15   7    23866554
16  11    26381542
17  18    41719364
18  14    22002630
19  16   215306076

# which images have -1 label

In [105]:
dict_of_img

{'rs00000.png': {0: 118415,
  1: 21653,
  2: 1116,
  5: 56914,
  8: 655556,
  9: 139285,
  10: 637307,
  12: 114931,
  13: 755,
  15: 254074,
  17: 53742,
  255: 19852},
 'rs00001.png': {0: 624717,
  1: 89822,
  2: 970974,
  3: 122994,
  4: 2949,
  5: 3924,
  6: 31,
  7: 1920,
  8: 35285,
  10: 269,
  11: 27388,
  13: 13682,
  18: 95845,
  255: 83800},
 'rs00002.png': {0: 489,
  1: 16878,
  2: 981643,
  4: 15726,
  5: 211504,
  8: 159767,
  9: 10216,
  10: 402473,
  12: 57190,
  15: 182232,
  17: 35482},
 'rs00003.png': {0: 57303,
  1: 216228,
  2: 61852,
  3: 606,
  4: 29848,
  5: 82905,
  7: 2714,
  8: 276499,
  9: 12360,
  10: 867605,
  11: 67680,
  12: 120753,
  13: 42176,
  15: 197095,
  17: 37421,
  18: 555},
 'rs00004.png': {0: 36709,
  1: 3451,
  2: 20179,
  3: 875,
  4: 615,
  5: 37387,
  6: 21,
  7: 394,
  8: 511819,
  9: 547785,
  10: 391688,
  12: 78609,
  14: 13961,
  15: 76974,
  17: 19104,
  18: 330,
  255: 333699},
 'rs00005.png': {0: 78252,
  1: 17596,
  2: 130932,
  4

In [133]:
img_minus_1=[]

In [136]:
for key,value in dict_of_img.items():
    item = dict_of_img[key]
    for labelKey,labelvalue in item.items():
        if  labelKey == 255:
            img_minus_1.append(key)

In [138]:
len(img_minus_1)

5902

In [126]:
test={'a':{-1:120, 0:130, 2:56}, 'b':{-1:160, 4:130, 2:56},'c': {3:120, 4:100, 2:56}}

In [127]:
test.items()

dict_items([('a', {-1: 120, 0: 130, 2: 56}), ('b', {-1: 160, 4: 130, 2: 56}), ('c', {3: 120, 4: 100, 2: 56})])

In [130]:
lis=[]
for key,value in test.items():
    item = test[key]
    for labelKey,labelvalue in item.items():
        if  labelKey == -1:
            lis.append(key)

In [131]:
lis

['a', 'b']

In [122]:
img_minus_1

[]

In [ ]:
minus_one={}

for key,value in dict_of_img.items():
    item = dict_of_img[key]
    for labelKey,labelvalue in item.items():
        if  labelKey == -1:
            minus_one[labelKey] = labelvalue    